openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /games/:
    get:
      operationId: games_list
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - games
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
          description: ''
    post:
      operationId: games_create
      description: A simple ViewSet for viewing and editing books.
      tags:
      - games
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Game'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Game'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
          description: ''
  /games/{id}/:
    get:
      operationId: games_retrieve
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this game.
        required: true
      tags:
      - games
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
          description: ''
    put:
      operationId: games_update
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this game.
        required: true
      tags:
      - games
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Game'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Game'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
          description: ''
    patch:
      operationId: games_partial_update
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this game.
        required: true
      tags:
      - games
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedGame'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedGame'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedGame'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
          description: ''
    delete:
      operationId: games_destroy
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this game.
        required: true
      tags:
      - games
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /platforms/:
    get:
      operationId: platforms_list
      description: A simple ViewSet for viewing and editing books.
      tags:
      - platforms
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Platform'
          description: ''
    post:
      operationId: platforms_create
      description: A simple ViewSet for viewing and editing books.
      tags:
      - platforms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Platform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Platform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Platform'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
          description: ''
  /platforms/{name}/:
    get:
      operationId: platforms_retrieve
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        description: A unique value identifying this platform.
        required: true
      tags:
      - platforms
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
          description: ''
    put:
      operationId: platforms_update
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        description: A unique value identifying this platform.
        required: true
      tags:
      - platforms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Platform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Platform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Platform'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
          description: ''
    patch:
      operationId: platforms_partial_update
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        description: A unique value identifying this platform.
        required: true
      tags:
      - platforms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPlatform'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
          description: ''
    delete:
      operationId: platforms_destroy
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        description: A unique value identifying this platform.
        required: true
      tags:
      - platforms
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /studios/:
    get:
      operationId: studios_list
      description: A simple ViewSet for viewing and editing books.
      tags:
      - studios
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Studio'
          description: ''
    post:
      operationId: studios_create
      description: A simple ViewSet for viewing and editing books.
      tags:
      - studios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Studio'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Studio'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Studio'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Studio'
          description: ''
  /studios/{name}/:
    get:
      operationId: studios_retrieve
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        description: A unique value identifying this studio.
        required: true
      tags:
      - studios
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Studio'
          description: ''
    put:
      operationId: studios_update
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        description: A unique value identifying this studio.
        required: true
      tags:
      - studios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Studio'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Studio'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Studio'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Studio'
          description: ''
    patch:
      operationId: studios_partial_update
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        description: A unique value identifying this studio.
        required: true
      tags:
      - studios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedStudio'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedStudio'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedStudio'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Studio'
          description: ''
    delete:
      operationId: studios_destroy
      description: A simple ViewSet for viewing and editing books.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        description: A unique value identifying this studio.
        required: true
      tags:
      - studios
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        release_date:
          type: string
          format: date
        ratings:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        studio:
          type: string
          nullable: true
        platform:
          type: array
          items:
            type: string
          readOnly: true
      required:
      - id
      - name
      - platform
      - ratings
      - release_date
    PatchedGame:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        release_date:
          type: string
          format: date
        ratings:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        studio:
          type: string
          nullable: true
        platform:
          type: array
          items:
            type: string
          readOnly: true
    PatchedPlatform:
      type: object
      properties:
        name:
          type: string
    PatchedStudio:
      type: object
      properties:
        name:
          type: string
    Platform:
      type: object
      properties:
        name:
          type: string
      required:
      - name
    Studio:
      type: object
      properties:
        name:
          type: string
      required:
      - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
